repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: format-py
    name: Format Python
    entry: make format
    types: [python]
    language: system
    pass_filenames: false
  - id: format-ts
    name: Format Typescript
    entry: npm run format
    types: [ts]
    language: system
    pass_filenames: false
  - id: lint-ts
    name: Lint Typescript
    entry: npm run lint
    types: [ts]
    language: system
    pass_filenames: false
  - id: build-js
    name: Build JS
    entry: npm run build
    types: [ts]
    language: system
    pass_filenames: false
